//! Native FFmpeg and durable-cache adapter for derived media artifacts.
//!
//! The webview sends validated, serializable requests and receives only file
//! locators plus metadata. Source media and generated bytes never cross IPC.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::io::{BufReader, Read};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::{Arc, Mutex};
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tauri::{AppHandle, Manager, State};

const ARTIFACT_DIRECTORY: &str = "media-artifacts";
const STAGING_DIRECTORY: &str = ".staging";
const WAVEFORM_HEIGHT: usize = 64;
const MAX_TASK_ID_LENGTH: usize = 128;

type SharedChild = Arc<Mutex<Child>>;

enum MediaProcessEntry {
    Pending,
    Running(SharedChild),
    Cancelled,
}

/// Process registry owned by Tauri state so cancellation never relies on a global singleton.
#[derive(Clone, Default)]
pub struct MediaProcessRegistry {
    children: Arc<Mutex<HashMap<String, MediaProcessEntry>>>,
}

impl MediaProcessRegistry {
    pub(crate) fn reserve(&self, task_id: &str) -> Result<(), String> {
        let mut children = self.children.lock().map_err(|_| {
            "The media process registry is unavailable. Restart VideoDip.".to_string()
        })?;
        if children
            .insert(task_id.to_string(), MediaProcessEntry::Pending)
            .is_some()
        {
            return Err(
                "A media task with this id is already running. Retry the operation.".to_string(),
            );
        }
        Ok(())
    }

    pub(crate) fn activate(&self, task_id: &str, child: SharedChild) -> Result<bool, String> {
        let mut children = self.children.lock().map_err(|_| {
            "The media process registry is unavailable. Restart VideoDip.".to_string()
        })?;
        match children.get(task_id) {
            Some(MediaProcessEntry::Pending) => {
                children.insert(task_id.to_string(), MediaProcessEntry::Running(child));
                Ok(false)
            }
            Some(MediaProcessEntry::Cancelled) => Ok(true),
            Some(MediaProcessEntry::Running(_)) | None => Err(
                "The media task registry changed unexpectedly. Retry the operation.".to_string(),
            ),
        }
    }

    pub(crate) fn cancel(&self, task_id: &str) -> Result<(), String> {
        let child = {
            let mut children = self.children.lock().map_err(|_| {
                "The media process registry is unavailable. Restart VideoDip.".to_string()
            })?;
            match children.get_mut(task_id) {
                Some(entry @ MediaProcessEntry::Pending) => {
                    *entry = MediaProcessEntry::Cancelled;
                    None
                }
                Some(MediaProcessEntry::Running(child)) => Some(child.clone()),
                Some(MediaProcessEntry::Cancelled) | None => None,
            }
        };
        if let Some(child) = child {
            child
                .lock()
                .map_err(|_| {
                    "The media process could not be cancelled. Restart VideoDip.".to_string()
                })?
                .kill()
                .map_err(|error| format!("Could not stop the media process: {error}"))?;
        }
        Ok(())
    }

    pub(crate) fn finish(&self, task_id: &str) -> Result<(), String> {
        self.children
            .lock()
            .map_err(|_| {
                "The media process registry is unavailable. Restart VideoDip.".to_string()
            })?
            .remove(task_id);
        Ok(())
    }
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerateMediaArtifactRequest {
    source: String,
    options: MediaArtifactOptions,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
enum MediaArtifactOptions {
    Thumbnail {
        time: f64,
        width: u32,
        height: u32,
        format: ThumbnailFormat,
    },
    Waveform {
        samples: usize,
    },
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "lowercase")]
enum ThumbnailFormat {
    Jpeg,
    Webp,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum MediaArtifact {
    Thumbnail {
        locator: String,
        content_type: String,
        size_bytes: u64,
        width: u32,
        height: u32,
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_key: Option<String>,
    },
    Waveform {
        locator: String,
        content_type: String,
        size_bytes: u64,
        sample_count: usize,
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_key: Option<String>,
    },
}

#[derive(Serialize)]
struct WaveformDocument<'a> {
    version: u32,
    peaks: &'a [f32],
}

/// Generates one thumbnail or waveform in the app-cache staging directory.
#[tauri::command]
pub async fn generate_media_artifact(
    app: AppHandle,
    registry: State<'_, MediaProcessRegistry>,
    task_id: String,
    request: GenerateMediaArtifactRequest,
) -> Result<MediaArtifact, String> {
    let registry = registry.inner().clone();
    tauri::async_runtime::spawn_blocking(move || generate(&app, &registry, &task_id, request))
        .await
        .map_err(|error| format!("The media artifact task crashed: {error}. Try again."))?
}

/// Terminates a running artifact process. Missing task ids are already cancelled/completed.
#[tauri::command]
pub fn cancel_media_artifact(
    registry: State<'_, MediaProcessRegistry>,
    task_id: String,
) -> Result<(), String> {
    validate_task_id(&task_id)?;
    registry.cancel(&task_id)
}

/// Returns a validated durable cache entry, or `null` after a cache miss.
#[tauri::command]
pub fn get_media_artifact_cache(
    app: AppHandle,
    cache_key: String,
) -> Result<Option<MediaArtifact>, String> {
    read_cached_artifact(&artifact_root(&app)?, &cache_key)
}

/// Atomically commits a generated staging artifact to the durable app cache.
#[tauri::command]
pub fn put_media_artifact_cache(
    app: AppHandle,
    cache_key: String,
    artifact: MediaArtifact,
) -> Result<MediaArtifact, String> {
    commit_artifact(&artifact_root(&app)?, &cache_key, artifact)
}

fn generate(
    app: &AppHandle,
    registry: &MediaProcessRegistry,
    task_id: &str,
    request: GenerateMediaArtifactRequest,
) -> Result<MediaArtifact, String> {
    validate_task_id(task_id)?;
    let source = Path::new(&request.source);
    if !source.is_file() {
        return Err("The source media file no longer exists. Re-import it and retry.".to_string());
    }
    let root = artifact_root(app)?;
    let staging = root.join(STAGING_DIRECTORY);
    fs::create_dir_all(&staging)
        .map_err(|error| format!("Could not create the media staging directory: {error}"))?;

    match request.options {
        MediaArtifactOptions::Thumbnail {
            time,
            width,
            height,
            format,
        } => generate_thumbnail(
            registry, task_id, source, &staging, time, width, height, format,
        ),
        MediaArtifactOptions::Waveform { samples } => {
            generate_waveform(registry, task_id, source, &staging, samples)
        }
    }
}

fn generate_thumbnail(
    registry: &MediaProcessRegistry,
    task_id: &str,
    source: &Path,
    staging: &Path,
    time_ms: f64,
    width: u32,
    height: u32,
    format: ThumbnailFormat,
) -> Result<MediaArtifact, String> {
    if !time_ms.is_finite()
        || time_ms < 0.0
        || width == 0
        || height == 0
        || width > 4096
        || height > 4096
    {
        return Err(
            "Thumbnail settings are invalid. Choose a valid time and size up to 4096 px."
                .to_string(),
        );
    }
    let (extension, codec, content_type) = match format {
        ThumbnailFormat::Jpeg => ("jpg", "mjpeg", "image/jpeg"),
        ThumbnailFormat::Webp => ("webp", "libwebp", "image/webp"),
    };
    let output = staging.join(format!("{task_id}.{extension}"));
    remove_file_if_present(&output)?;
    let args = thumbnail_args(source, &output, time_ms, width, height, codec);
    run_ffmpeg(registry, task_id, &args, false)?;
    let size_bytes = file_size(&output, "thumbnail")?;
    Ok(MediaArtifact::Thumbnail {
        locator: path_string(&output),
        content_type: content_type.to_string(),
        size_bytes,
        width,
        height,
        cache_key: None,
    })
}

fn generate_waveform(
    registry: &MediaProcessRegistry,
    task_id: &str,
    source: &Path,
    staging: &Path,
    samples: usize,
) -> Result<MediaArtifact, String> {
    if !(16..=100_000).contains(&samples) {
        return Err("Waveform sample count must be between 16 and 100000.".to_string());
    }
    let args = waveform_args(source, samples);
    let pixels = run_ffmpeg(registry, task_id, &args, true)?;
    let expected = samples
        .checked_mul(WAVEFORM_HEIGHT)
        .ok_or_else(|| "Waveform dimensions overflowed. Choose fewer samples.".to_string())?;
    if pixels.len() != expected {
        return Err(format!(
            "FFmpeg returned an incomplete waveform ({} bytes, expected {expected}). Try a different audio source.",
            pixels.len()
        ));
    }
    let peaks = waveform_peaks(&pixels, samples, WAVEFORM_HEIGHT);
    let output = staging.join(format!("{task_id}.waveform.json"));
    remove_file_if_present(&output)?;
    let document = serde_json::to_vec(&WaveformDocument {
        version: 1,
        peaks: &peaks,
    })
    .map_err(|error| format!("Could not encode the generated waveform: {error}"))?;
    fs::write(&output, document)
        .map_err(|error| format!("Could not write the generated waveform: {error}"))?;
    let size_bytes = file_size(&output, "waveform")?;
    Ok(MediaArtifact::Waveform {
        locator: path_string(&output),
        content_type: "application/vnd.videodip.waveform+json".to_string(),
        size_bytes,
        sample_count: samples,
        cache_key: None,
    })
}

fn thumbnail_args(
    source: &Path,
    output: &Path,
    time_ms: f64,
    width: u32,
    height: u32,
    codec: &str,
) -> Vec<String> {
    vec![
        "-hide_banner".into(),
        "-loglevel".into(),
        "error".into(),
        "-y".into(),
        "-ss".into(),
        format!("{:.6}", time_ms / 1000.0),
        "-i".into(),
        path_string(source),
        "-frames:v".into(),
        "1".into(),
        "-vf".into(),
        format!("scale={width}:{height}:force_original_aspect_ratio=decrease,pad={width}:{height}:(ow-iw)/2:(oh-ih)/2"),
        "-c:v".into(),
        codec.into(),
        path_string(output),
    ]
}

fn waveform_args(source: &Path, samples: usize) -> Vec<String> {
    vec![
        "-hide_banner".into(),
        "-loglevel".into(),
        "error".into(),
        "-i".into(),
        path_string(source),
        "-filter_complex".into(),
        format!("aformat=channel_layouts=mono,showwavespic=s={samples}x{WAVEFORM_HEIGHT}:colors=white,format=gray"),
        "-frames:v".into(),
        "1".into(),
        "-f".into(),
        "rawvideo".into(),
        "-pix_fmt".into(),
        "gray".into(),
        "pipe:1".into(),
    ]
}

fn run_ffmpeg(
    registry: &MediaProcessRegistry,
    task_id: &str,
    args: &[String],
    capture_stdout: bool,
) -> Result<Vec<u8>, String> {
    registry.reserve(task_id)?;
    let mut command = Command::new("ffmpeg");
    command
        .args(args)
        .stdin(Stdio::null())
        .stdout(if capture_stdout {
            Stdio::piped()
        } else {
            Stdio::null()
        })
        .stderr(Stdio::piped());
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        command.creation_flags(CREATE_NO_WINDOW);
    }

    let mut child = match command.spawn() {
        Ok(child) => child,
        Err(error) => {
            registry.finish(task_id)?;
            return Err(if error.kind() == std::io::ErrorKind::NotFound {
                "FFmpeg was not found. Install FFmpeg, then retry media generation.".to_string()
            } else {
                format!("Could not start FFmpeg: {error}. Try again.")
            });
        }
    };
    let stdout_reader = child.stdout.take().map(|stdout| {
        std::thread::spawn(move || {
            let mut bytes = Vec::new();
            let _ = BufReader::new(stdout).read_to_end(&mut bytes);
            bytes
        })
    });
    let stderr_reader = child.stderr.take().map(|stderr| {
        std::thread::spawn(move || {
            let mut text = String::new();
            let _ = BufReader::new(stderr).read_to_string(&mut text);
            text
        })
    });
    let child = Arc::new(Mutex::new(child));
    let was_cancelled = registry.activate(task_id, child.clone())?;
    if was_cancelled {
        child
            .lock()
            .map_err(|_| "The media process could not be cancelled. Restart VideoDip.".to_string())?
            .kill()
            .map_err(|error| format!("Could not stop media generation: {error}"))?;
    }

    let status = loop {
        let status = child
            .lock()
            .map_err(|_| "The media process became unavailable. Retry the operation.".to_string())?
            .try_wait()
            .map_err(|error| format!("Could not monitor FFmpeg: {error}"))?;
        if let Some(status) = status {
            break status;
        }
        std::thread::sleep(Duration::from_millis(25));
    };
    registry.finish(task_id)?;

    let stdout = stdout_reader
        .and_then(|reader| reader.join().ok())
        .unwrap_or_default();
    let stderr = stderr_reader
        .and_then(|reader| reader.join().ok())
        .unwrap_or_default();
    if status.success() {
        Ok(stdout)
    } else {
        Err(format!(
            "FFmpeg could not generate this media artifact:\n{}\nTry a different source or codec.",
            stderr_tail(&stderr)
        ))
    }
}

fn waveform_peaks(pixels: &[u8], width: usize, height: usize) -> Vec<f32> {
    let center = (height.saturating_sub(1)) as f32 / 2.0;
    (0..width)
        .map(|x| {
            let distance = (0..height)
                .filter(|y| pixels[y * width + x] > 0)
                .map(|y| ((y as f32) - center).abs())
                .fold(0.0_f32, f32::max);
            if center > 0.0 {
                (distance / center).clamp(0.0, 1.0)
            } else {
                0.0
            }
        })
        .collect()
}

fn commit_artifact(
    root: &Path,
    cache_key: &str,
    artifact: MediaArtifact,
) -> Result<MediaArtifact, String> {
    if cache_key.is_empty() {
        return Err("Media cache keys must not be empty.".to_string());
    }
    fs::create_dir_all(root)
        .map_err(|error| format!("Could not create the media cache directory: {error}"))?;
    let staging_root = root.join(STAGING_DIRECTORY);
    fs::create_dir_all(&staging_root)
        .map_err(|error| format!("Could not create the media staging directory: {error}"))?;
    let source = artifact_locator(&artifact);
    let canonical_source = fs::canonicalize(source)
        .map_err(|error| format!("The generated media artifact is missing: {error}"))?;
    let canonical_staging = fs::canonicalize(&staging_root)
        .map_err(|error| format!("Could not validate the media staging directory: {error}"))?;
    if !canonical_source.starts_with(&canonical_staging) || !canonical_source.is_file() {
        return Err("Refused to cache a file outside VideoDip's staging directory.".to_string());
    }

    let hash = cache_hash(cache_key);
    let final_directory = root.join(&hash);
    if final_directory.exists() {
        fs::remove_file(&canonical_source).ok();
        return read_cached_artifact(root, cache_key)?.ok_or_else(|| {
            "The existing media cache entry is invalid. Clear generated media data and retry."
                .to_string()
        });
    }
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let pending = root.join(format!(".{hash}.{}.{}.tmp", std::process::id(), nonce));
    fs::create_dir(&pending)
        .map_err(|error| format!("Could not prepare a media cache commit: {error}"))?;
    let extension = artifact_extension(&artifact);
    let final_file = final_directory.join(format!("artifact.{extension}"));
    let pending_file = pending.join(format!("artifact.{extension}"));
    fs::rename(&canonical_source, &pending_file)
        .map_err(|error| format!("Could not stage the generated media artifact: {error}"))?;
    let cached = with_cache_identity(artifact, cache_key, &final_file);
    let metadata = serde_json::to_vec(&cached)
        .map_err(|error| format!("Could not encode media cache metadata: {error}"))?;
    fs::write(pending.join("metadata.json"), metadata)
        .map_err(|error| format!("Could not write media cache metadata: {error}"))?;
    match fs::rename(&pending, &final_directory) {
        Ok(()) => Ok(cached),
        Err(_error) if final_directory.exists() => {
            fs::remove_dir_all(&pending).ok();
            read_cached_artifact(root, cache_key)?.ok_or_else(|| {
                "A concurrent media cache commit produced an invalid entry. Retry the operation."
                    .to_string()
            })
        }
        Err(error) => {
            fs::remove_dir_all(&pending).ok();
            Err(format!(
                "Could not commit the generated media artifact: {error}"
            ))
        }
    }
}

fn read_cached_artifact(root: &Path, cache_key: &str) -> Result<Option<MediaArtifact>, String> {
    let directory = root.join(cache_hash(cache_key));
    let metadata_path = directory.join("metadata.json");
    if !metadata_path.is_file() {
        return Ok(None);
    }
    let bytes = fs::read(&metadata_path)
        .map_err(|error| format!("Could not read media cache metadata: {error}"))?;
    let artifact: MediaArtifact = serde_json::from_slice(&bytes)
        .map_err(|error| format!("Media cache metadata is invalid: {error}"))?;
    if artifact_cache_key(&artifact) != Some(cache_key) {
        return Err("Media cache identity does not match its storage key. Clear generated media data and retry.".to_string());
    }
    let file = Path::new(artifact_locator(&artifact));
    if !file.is_file() || !file.starts_with(&directory) {
        return Err("The cached media artifact file is missing or unsafe. Clear generated media data and retry.".to_string());
    }
    let actual_size = file_size(file, "cached media artifact")?;
    if actual_size != artifact_size(&artifact) {
        return Err(
            "The cached media artifact size changed. Clear generated media data and retry."
                .to_string(),
        );
    }
    Ok(Some(artifact))
}

fn artifact_root(app: &AppHandle) -> Result<PathBuf, String> {
    app.path()
        .app_cache_dir()
        .map(|path| path.join(ARTIFACT_DIRECTORY))
        .map_err(|error| format!("Could not resolve the VideoDip media cache directory: {error}"))
}

fn cache_hash(value: &str) -> String {
    const OFFSET: u128 = 0x6c62272e07bb014262b821756295c58d;
    const PRIME: u128 = 0x0000000001000000000000000000013b;
    let hash = value.as_bytes().iter().fold(OFFSET, |hash, byte| {
        (hash ^ u128::from(*byte)).wrapping_mul(PRIME)
    });
    format!("{hash:032x}")
}

pub(crate) fn validate_task_id(task_id: &str) -> Result<(), String> {
    if task_id.is_empty()
        || task_id.len() > MAX_TASK_ID_LENGTH
        || !task_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
    {
        return Err("Media task id is invalid. Retry the operation.".to_string());
    }
    Ok(())
}

fn artifact_locator(artifact: &MediaArtifact) -> &str {
    match artifact {
        MediaArtifact::Thumbnail { locator, .. } | MediaArtifact::Waveform { locator, .. } => {
            locator
        }
    }
}

fn artifact_cache_key(artifact: &MediaArtifact) -> Option<&str> {
    match artifact {
        MediaArtifact::Thumbnail { cache_key, .. } | MediaArtifact::Waveform { cache_key, .. } => {
            cache_key.as_deref()
        }
    }
}

fn artifact_size(artifact: &MediaArtifact) -> u64 {
    match artifact {
        MediaArtifact::Thumbnail { size_bytes, .. }
        | MediaArtifact::Waveform { size_bytes, .. } => *size_bytes,
    }
}

fn artifact_extension(artifact: &MediaArtifact) -> &'static str {
    match artifact {
        MediaArtifact::Thumbnail { content_type, .. } if content_type == "image/webp" => "webp",
        MediaArtifact::Thumbnail { .. } => "jpg",
        MediaArtifact::Waveform { .. } => "waveform.json",
    }
}

fn with_cache_identity(artifact: MediaArtifact, cache_key: &str, locator: &Path) -> MediaArtifact {
    match artifact {
        MediaArtifact::Thumbnail {
            content_type,
            size_bytes,
            width,
            height,
            ..
        } => MediaArtifact::Thumbnail {
            locator: path_string(locator),
            content_type,
            size_bytes,
            width,
            height,
            cache_key: Some(cache_key.to_string()),
        },
        MediaArtifact::Waveform {
            content_type,
            size_bytes,
            sample_count,
            ..
        } => MediaArtifact::Waveform {
            locator: path_string(locator),
            content_type,
            size_bytes,
            sample_count,
            cache_key: Some(cache_key.to_string()),
        },
    }
}

fn file_size(path: &Path, label: &str) -> Result<u64, String> {
    let size = fs::metadata(path)
        .map_err(|error| format!("Could not inspect the generated {label}: {error}"))?
        .len();
    if size == 0 {
        return Err(format!(
            "FFmpeg produced an empty {label}. Try a different source or codec."
        ));
    }
    Ok(size)
}

fn remove_file_if_present(path: &Path) -> Result<(), String> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(format!(
            "Could not clear an old staged media artifact: {error}"
        )),
    }
}

fn path_string(path: &Path) -> String {
    path.to_string_lossy().into_owned()
}

fn stderr_tail(stderr: &str) -> String {
    stderr
        .lines()
        .rev()
        .take(8)
        .collect::<Vec<_>>()
        .into_iter()
        .rev()
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_ids_cannot_escape_staging() {
        assert!(validate_task_id("task-123_ok").is_ok());
        assert!(validate_task_id("../escape").is_err());
        assert!(validate_task_id("").is_err());
    }

    #[test]
    fn cache_hash_is_stable_and_path_safe() {
        assert_eq!(cache_hash("same"), cache_hash("same"));
        assert_ne!(cache_hash("same"), cache_hash("different"));
        assert_eq!(cache_hash("a/b").len(), 32);
        assert!(cache_hash("a/b")
            .bytes()
            .all(|byte| byte.is_ascii_hexdigit()));
    }

    #[test]
    fn waveform_pixels_become_bounded_peaks() {
        let pixels = [255, 0, 0, 255, 0, 0, 0, 0];
        let peaks = waveform_peaks(&pixels, 2, 4);
        assert_eq!(peaks.len(), 2);
        assert!(peaks.iter().all(|peak| (0.0..=1.0).contains(peak)));
        assert!(peaks[0] > peaks[1]);
    }

    #[test]
    fn ffmpeg_arguments_do_not_use_a_shell() {
        let thumbnail = thumbnail_args(
            Path::new("source with spaces.mp4"),
            Path::new("output.jpg"),
            1_500.0,
            320,
            180,
            "mjpeg",
        );
        assert!(thumbnail.contains(&"source with spaces.mp4".to_string()));
        assert!(thumbnail.contains(&"1.500000".to_string()));
        let waveform = waveform_args(Path::new("audio.wav"), 512);
        assert!(waveform
            .iter()
            .any(|argument| argument.contains("s=512x64")));
    }

    #[test]
    fn cancellation_is_remembered_before_process_activation() {
        let registry = MediaProcessRegistry::default();
        registry.reserve("export-1").expect("task should reserve");
        registry
            .cancel("export-1")
            .expect("pending task should cancel");

        let children = registry.children.lock().expect("registry should lock");
        assert!(matches!(
            children.get("export-1"),
            Some(MediaProcessEntry::Cancelled)
        ));
    }

    #[test]
    fn duplicate_task_ids_are_rejected() {
        let registry = MediaProcessRegistry::default();
        registry.reserve("task-1").expect("task should reserve");
        assert!(registry.reserve("task-1").is_err());
    }
}
