export type {
  Clip,
  ClipBlendMode,
  ClipAnimationProperty,
  ClipAudioSettings,
  ClipKeyframe,
  ClipKeyframeEasing,
  ClipMetadata,
  ClipTransform,
  ClipTransition,
  CoreTransitionKind,
  Track,
  TimelineDocument,
  TrackKind,
  TransitionKind,
} from './document.types.js';
export {
  CORE_TRANSITION_KINDS,
  DEFAULT_CLIP_TRANSFORM,
  DEFAULT_CLIP_AUDIO,
  DEFAULT_CLIP_VISUALS,
  addClip,
  addTransition,
  addTrack,
  createTimeline,
  createTrack,
  findFreeStart,
  evaluateClipProperty,
  getDuration,
  moveClip,
  removeClip,
  removeTrack,
  removeTransition,
  reorderTrack,
  splitClip,
  setClipAnimation,
  trimClip,
  updateClipAudio,
  updateClipProperties,
  updateTransition,
  type AddClipInput,
  type AddTransitionInput,
  type CreateTrackInput,
  type TrimEdge,
  type UpdateClipPropertiesInput,
  type UpdateTransitionInput,
} from './document.service.js';
